blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.AddPostView.as_view(), name='add_post'),
    path('edit/<int:pk>/', views.UpdatePostView.as_view(), name='update_post'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete_post'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_Category'),
    path('category/<str:cats>/', views.category_view, name='category'),
    path('category_list/', views.category_list_view, name='category_list'),
    path('post_like/<int:pk>/', views.post_like_view, name='post_like'),
]

blog_web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('member/',include('django.contrib.auth.urls')),
    path('member/', include('member.urls')),
    path('social-auth', include('social_django.urls', namespace='social')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'member'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('edit_profile/', views.UserEditView.as_view(), name='profile_edit'),

    # change password
    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
    #      name='password_change_done'),

    #custom change password
    path('password_change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('user_profile/<int:pk>', views.UserProfilePageView.as_view(),
         name='user_profile'),
    path('edit_profile/<int:pk>/', views.EditProfilePageView.as_view(),
         name='edit_profile'),



]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list')


# extend the User profile
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to='images/profile')
    website_url = models.CharField(null=True, blank=True, max_length=255)
    facebook_url = models.CharField(null=True, blank=True, max_length=255)
    twitter_url = models.CharField(null=True, blank=True, max_length=255)


    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('blog:post_list')


class Post(models.Model):
    title = models.CharField(max_length=250)
    header_image = models.ImageField(null=True, blank=True, upload_to='images/')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts')

    # body using ckeditor
    body = RichTextField(blank=True, null=True)
    # body = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=255, default= ' uncategorized')
    snippet  = models.CharField(max_length=255, default='click above link to read blog post...')
    likes = models.ManyToManyField(User, related_name='post_user_like')

    def __str__(self):
        return self.title  + ' | ' + str(self.author)

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blog:post_list')

blog/forms.py
from django import forms
from .models import Post, Category


choices = Category.objects.all().values_list('name', 'name')

# convert django queryset response into list
choices_list = []
for item in choices:
    choices_list.append(item)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'category', 'body','snippet', 'header_image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'This is title section'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choices_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'})
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'body', 'snippet')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choices_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category
from .forms import PostForm, EditForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
# Create your views here.


class HomeView(ListView):
    model = Post
    template_name = 'blog/post/post_list.html'
    ordering = ('-id')

    def get_context_data(self, *args, object_list=None, **kwargs):
        cats_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context['cats_menu'] = cats_menu
        return context


class PostDetailView(DetailView):
    DetailView.model = Post
    template_name = 'blog/post/post_detail.html'

    def get_context_data(self,*args, **kwargs):
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        stuff = get_object_or_404(Post, id = self.kwargs['pk'])
        total_likes = stuff.total_likes()
        context['total_likes'] = total_likes

        liked = False
        if stuff.likes.filter(id = self.request.user.id).exists():
            liked = True
        context['liked'] = liked
        print('context value', context)
        return context


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post/add_post.html'


class AddCategoryView(CreateView):
    model = Category
    fields = '__all__'
    template_name = 'blog/post/add_category.html'


class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'blog/post/upate_post.html'


class DeletePostView(DeleteView):
    model = Post
    template_name = 'blog/post/delete_post.html'
    success_url = reverse_lazy('blog:post_list')


def category_view(request, cats):
    category_posts = Post.objects.filter(category=cats.replace('-', ' '))
    context = {
        'category_posts': category_posts,
        'cats': cats
    }
    return render(request, 'blog/post/category.html', context,)


def category_list_view(request):
    cats_list = Category.objects.all()
    context = {'cats_list': cats_list}
    return render(request, 'blog/post/category_list.html', context)


def post_like_view(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    # request contains user id if logged in
    if post.likes.filter(id = request.user.id).exists():
        # user already liked, unlike now
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    # post.likes.add(request.user)
    return HttpResponseRedirect(reverse('blog:post_detail', args=[str(pk)]))

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}Its my blog website{% endblock %}</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:post_list' %}">This is blog posting website</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            {% if cats_menu %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for item in cats_menu %}
                            <a class="dropdown-item" href="{% url 'blog:category' item %}">{{ item }}</a>
                        {% endfor %}
                    </div>
                </li>
            {% else %}
                <a class="nav-link" href="{% url 'blog:category_list' %}">Categories</a>
            {% endif %}

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:add_Category' %}">Add Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:add_post' %}">Add post</a>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'member:profile_edit' %}">Edit Settings</a>
                        {% if user.profile.id %}
                            <a class="dropdown-item" href="{% url 'member:edit_profile' user.profile.id %}">Edit
                                Profile</a>
                            <a class="dropdown-item" href="{% url 'member:user_profile' user.profile.id %}">Show
                                Profile</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url '' %}">Create Profile</a>

                        {% endif %}

                    </div>
                </li>




                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'member:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}

        <h1>Hello, world!</h1>
        {{ cats_menu }}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>