blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.AddPostView.as_view(), name='add_post'),
    path('edit/<int:pk>/', views.UpdatePostView.as_view(), name='update_post'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete_post'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_Category'),
    path('category/<str:cats>/', views.category_view, name='category'),
    path('category_list/', views.category_list_view, name='category_list'),
    path('post_like/<int:pk>/', views.post_like_view, name='post_like'),
]

blog_web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('member/',include('django.contrib.auth.urls')),
    path('member/', include('member.urls')),
    path('social-auth', include('social_django.urls', namespace='social')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'member'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('edit_profile/', views.UserEditView.as_view(), name='profile_edit'),

    # change password
    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
    #      name='password_change_done'),

    #custom change password
    path('password_change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('user_profile/<int:pk>', views.UserProfilePageView.as_view(),
         name='user_profile'),
    path('edit_profile/<int:pk>/', views.EditProfilePageView.as_view(),
         name='edit_profile'),



]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list')


# extend the User profile
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to='images/profile')
    website_url = models.CharField(null=True, blank=True, max_length=255)
    facebook_url = models.CharField(null=True, blank=True, max_length=255)
    twitter_url = models.CharField(null=True, blank=True, max_length=255)


    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('blog:post_list')


class Post(models.Model):
    title = models.CharField(max_length=250)
    header_image = models.ImageField(null=True, blank=True, upload_to='images/')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts')

    # body using ckeditor
    body = RichTextField(blank=True, null=True)
    # body = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=255, default= ' uncategorized')
    snippet  = models.CharField(max_length=255, default='click above link to read blog post...')
    likes = models.ManyToManyField(User, related_name='post_user_like')

    def __str__(self):
        return self.title  + ' | ' + str(self.author)

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blog:post_list')

blog/forms.py
from django import forms
from .models import Post, Category


choices = Category.objects.all().values_list('name', 'name')

# convert django queryset response into list
choices_list = []
for item in choices:
    choices_list.append(item)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'category', 'body','snippet', 'header_image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'This is title section'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choices_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'})
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'body', 'snippet')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choices_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category
from .forms import PostForm, EditForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
# Create your views here.


class HomeView(ListView):
    model = Post
    template_name = 'blog/post/post_list.html'
    ordering = ('-id')

    def get_context_data(self, *args, object_list=None, **kwargs):
        cats_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context['cats_menu'] = cats_menu
        return context


class PostDetailView(DetailView):
    DetailView.model = Post
    template_name = 'blog/post/post_detail.html'

    def get_context_data(self,*args, **kwargs):
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        stuff = get_object_or_404(Post, id = self.kwargs['pk'])
        total_likes = stuff.total_likes()
        context['total_likes'] = total_likes

        liked = False
        if stuff.likes.filter(id = self.request.user.id).exists():
            liked = True
        context['liked'] = liked
        print('context value', context)
        return context


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post/add_post.html'


class AddCategoryView(CreateView):
    model = Category
    fields = '__all__'
    template_name = 'blog/post/add_category.html'


class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'blog/post/upate_post.html'


class DeletePostView(DeleteView):
    model = Post
    template_name = 'blog/post/delete_post.html'
    success_url = reverse_lazy('blog:post_list')


def category_view(request, cats):
    category_posts = Post.objects.filter(category=cats.replace('-', ' '))
    context = {
        'category_posts': category_posts,
        'cats': cats
    }
    return render(request, 'blog/post/category.html', context,)


def category_list_view(request):
    cats_list = Category.objects.all()
    context = {'cats_list': cats_list}
    return render(request, 'blog/post/category_list.html', context)


def post_like_view(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    # request contains user id if logged in
    if post.likes.filter(id = request.user.id).exists():
        # user already liked, unlike now
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    # post.likes.add(request.user)
    return HttpResponseRedirect(reverse('blog:post_detail', args=[str(pk)]))

blog/templates/blog/post/add_category.html
{% extends 'blog/base.html' %}

{% block title %}Add Category {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Add Category</h1>
        <br><br>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary">Add category</button>
        </form>

    {% else %}
        <h2> You are not allowed to add category </h2>
    {% endif %}
{% endblock %}

blog/templates/blog/post/add_post.html
{% extends 'blog/base.html' %}

{% block title %}Add post {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Add post</h1>
        <br><br>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-primary">Post</button>
        </form>

    {% else %}
        <h2> you are not allowed to add post</h2>
    {% endif %}
{% endblock %}

blog/templates/blog/post/category.html
{% extends 'blog/base.html' %}
{% block content %}
    {% if category_posts %}
    <h1>{{ cats }} Categories</h1>

    {% for post in category_posts %}
        <li><a href='{% url 'blog:post_detail' post.pk %}'>{{ post.title }}</a>
           - {{ post.author }}
        -{{ post.category }} -
            {% if user.is_authenticated %}
                <a href="{% url 'blog:update_post' post.pk %}">Edit</a> -
                <a href="{% url 'blog:delete_post' post.pk %}">Delete</a>
            {% endif %}
        </li>
        <li>{{ post.body }}</li>
    {% endfor %}
    {% else %}
        <h2>There is not any post related to this category</h2>
    {% endif %}
{% endblock %}

blog/templates/blog/post/category_list.html
{% extends 'blog/base.html' %}
{% block title %}Category title{% endblock %}

{% block content %}
    <h1>Categories</h1>

    {% for item in cats_list %}
        <h3><a href="{% url 'blog:category' item %}">{{ item }}</a></h3>
    {% endfor %}
{% endblock %}

blog/templates/blog/post/delete_post.html
{% extends 'blog/base.html' %}

{% block title %}Delete post {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
            <h1>Delete post</h1>
            <br><br>
            <h3>Delete: {{ post.tittle }}</h3>
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    <strong>Are you sure u want to delete</strong>
                    <button class="btn btn-danger">Delete Post</button>
                </form>
            </div>

        {% endif %}
    {% else %}
        <h2>You are not allowed here</h2>
    {% endif %}
{% endblock %}

blog/templates/blog/post/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.author }} - {{ post.post_date }}
        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                <a href="{% url 'blog:update_post' post.pk %}">Edit</a>
                <a href="{% url 'blog:delete_post' post.pk %}">Delete</a>
            {% endif %}
        {% endif %}
    </p>
    {% if post.header_image %}
        <img src="{{ post.header_image.url }}" height="200" width="200"><br><br>
    {% endif %}
    <p>{{ post.body | safe }}</p>
    <br>
    <a class='btn btn-primary' href="{% url 'blog:post_list' %}">Back</a>

    <br><br>
    <form action="{% url 'blog:post_like' post.pk %}" method="POST">
        {% csrf_token %}
        {% if user.is_authenticated %}
            {% if liked %}
                <button type="submit" name="post_id" value="{{ post.id }}"
                        class="btn btn-danger btn-sm">UnLike
                </button>
            {% else %}
                <button type="submit" name="post_id" value="{{ post.id }}"
                        class="btn btn-primary btn-sm">Like
                </button>
            {% endif %}
            {{ total_likes }}
        {% else %}
            <h3>Must be logged in to like the post</h3>
        {% endif %}
    </form>
    <br><br>
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-2">
                {% if post.author.profile.profile_pic %}
                    <img src="{{ post.author.profile.profile_pic.url }}" class="card-img">
                {% else %}
                    <img src="{% static 'blog/images/default-profile-pic.png' %}"
                         class="card-img">
                {% endif %}
            </div>
            <div class="col-md-10">
                <div class="card-body">
                    <h5 class="card-title">{{ post.author.username }}</h5>
                    <p class="small text-muted">

                        <a href="{% url 'member:user_profile' post.author.profile.id %}">Profile Page</a>
                        {% if post.author.profile.facebook_url %}
                         |   <a href="{{ post.author.profile.facebook_url }}">facebook</a> |
                        {% endif %}
                        {% if post.author.profile.website_url %}
                            <a href="{{ post.author.profile.website_url }}">website</a> |
                        {% endif %}
                        {% if post.author.profile.twitter_url %}
                            <a href="{{ post.author.profile.twitter_url }}">twitter</a>
                        {% endif %}
                    </p>
                    <p class="card-text">{{ post.author.profile.bio }}</p>
                    {#                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>#}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>Post</h1>

    {% for post in post_list %}
        <li><a href='{% url 'blog:post_detail' post.pk %}'>{{ post.title }}</a>
            - {{ post.author }}
            -<a href="{% url 'blog:category' post.category %}">{{ post.category }}</a> -
            {% if user.is_authenticated %}
                {% if user.id == post.author.id %}
                    <a href="{% url 'blog:update_post' post.pk %}">Edit</a> -
                    <a href="{% url 'blog:delete_post' post.pk %}">Delete</a>
                {% endif %}
            {% endif %}
        </li>
        {{ post.snippet }}

    {% endfor %}
{% endblock %}

blog/templates/blog/post/upate_post.html
{% extends 'blog/base.html' %}

{% block title %}Update post {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
        <h1>Update post</h1>
        <br><br>
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
               {{form.media}}
                {{ form.as_p }}
                <button class="btn btn-primary">Update</button>
            </form>
        </div>
            {% endif %}
    {% else %}
        <h2>You don't have access to edit the post</h2>
    {% endif %}
{% endblock %}